execution: "serial"
bench_cases:
   - name: "insert-person"
     concurrency: 100
     time: 10
   - name: "insert-friend"
     concurrency: 100
     time: 10
    # - name: "get-friends-one-hop"
    #   concurrency: 100
#    - name: "get-friends-two-hop"
#      concurrency: 100
