{
 "title": "Insert Person",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Percentile Distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(dgraph_people_query_duration_bucket[5m])) by (le))",
     "legendFormat": "99 percentille"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dgraph_people_query_duration_bucket[5m])) by (le))",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(dgraph_people_query_duration_bucket[5m])) by (le))",
     "legendFormat": "90 percentile"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(dgraph_people_query_duration_bucket[5m])) by (le))",
     "legendFormat": "80 percentile"
    }
   ]
  },
  {
   "title": "Mutation Per Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dgraph_people_query_count[5m])",
     "legendFormat": "Query Rate"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dgraph_people_query_throughput", "legendFormat": "speed per second" }
   ]
  },
  {
   "title": "average request duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dgraph_people_query_duration_sum[5m])\n/\n  rate(dgraph_people_query_duration_count[5m])",
     "legendFormat": "average request time"
    }
   ]
  }
 ]
}